const countries = [
  {
    country: "Afghanistan",
    capital: "Kabul",
    image: "./countries/afghanistan-silhouette-thumbnail.png",
    lat: 34.5553,
    lon: 69.2075,
    bounds: {
      minLat: 29.0,
      maxLat: 38.5,
      minLon: 60.5,
      maxLon: 75.0,
    },
  },
  {
    country: "Algeria",
    capital: "Algiers",
    image: "./countries/algeria-silhouette-thumbnail.png",
    lat: 36.7538,
    lon: 3.0588,
    bounds: {
      minLat: 19.0,
      maxLat: 37.5,
      minLon: -9.6,
      maxLon: 12.0,
    },
  },
  {
    country: "Andorra",
    capital: "Andorra la Vella",
    image: "./countries/andorra-silhouette-thumbnail.png",
    lat: 42.5078,
    lon: 1.5211,
    bounds: {
      minLat: 42.4,
      maxLat: 42.7,
      minLon: 1.3,
      maxLon: 1.7,
    },
  },
  {
    country: "Argentina",
    capital: "Buenos Aires",
    image: "./countries/argentina-silhouette-thumbnail.png",
    lat: -34.6037,
    lon: -58.3816,
    bounds: {
      minLat: -55.0,
      maxLat: -21.0,
      minLon: -73.5,
      maxLon: -53.0,
    },
  },
  {
    country: "Australia",
    capital: "Canberra",
    image: "../countries/australia-silhouette-thumbnail.png",
    lat: -35.2809,
    lon: 149.1300,
    bounds: {
      minLat: -44.0,
      maxLat: -10.0,
      minLon: 112.0,
      maxLon: 154.0,
    },
  },
  {
    country: "Austria",
    capital: "Vienna",
    image: "./countries/austria-silhouette-thumbnail.png",
    lat: 48.2082,
    lon: 16.3738,
    bounds: {
      minLat: 46.2,
      maxLat: 49.0,
      minLon: 9.5,
      maxLon: 17.5,
    },
  },
  {
    country: "Bahrain",
    capital: "Manama",
    image: "./countries/bahrain-silhouette-thumbnail.png",
    lat: 26.2235,
    lon: 50.5876,
    bounds: {
      minLat: 26.0,
      maxLat: 26.5,
      minLon: 50.4,
      maxLon: 50.8,
    },
  },
  {
    country: "Bangladesh",
    capital: "Dhaka",
    image: "./countries/bangladesh-silhouette-thumbnail.png",
    lat: 23.8103,
    lon: 90.4125,
    bounds: {
      minLat: 20.7,
      maxLat: 26.6,
      minLon: 88.0,
      maxLon: 92.7,
    },
  },
  {
    country: "Belgium",
    capital: "Brussels",
    image: "./countries/belgium-silhouette-thumbnail.png",
    lat: 50.8503,
    lon: 4.3517,
    bounds: {
      minLat: 49.5,
      maxLat: 51.5,
      minLon: 2.5,
      maxLon: 6.5,
    },
  },
{
  country: "France",
  capital: "Paris",
  image: "./countries/france-silhouette-thumbnail.png",
  coloredImage: "./countriesColoured/franceColoured.jpg", // You can update the image path to match the correct country
  lat: 48.8566,
  lon: 2.3522,
  bounds: {
    minLat: 48.7,
    maxLat: 49.0,
    minLon: 2.2,
    maxLon: 2.5,
    },
  },
];

export default countries;
